package jp.co.hjn.merryapi.infrastructure.model;

import java.util.Date;

public class DayOff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_off.id
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_off.employee_id
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_off.start_date
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_off.end_date
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_off.created_at
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_off.updated_at
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column day_off.deleted_at
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    private Date deletedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_off.id
     *
     * @return the value of day_off.id
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_off.id
     *
     * @param id the value for day_off.id
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_off.employee_id
     *
     * @return the value of day_off.employee_id
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_off.employee_id
     *
     * @param employeeId the value for day_off.employee_id
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_off.start_date
     *
     * @return the value of day_off.start_date
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_off.start_date
     *
     * @param startDate the value for day_off.start_date
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_off.end_date
     *
     * @return the value of day_off.end_date
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_off.end_date
     *
     * @param endDate the value for day_off.end_date
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_off.created_at
     *
     * @return the value of day_off.created_at
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_off.created_at
     *
     * @param createdAt the value for day_off.created_at
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_off.updated_at
     *
     * @return the value of day_off.updated_at
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_off.updated_at
     *
     * @param updatedAt the value for day_off.updated_at
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column day_off.deleted_at
     *
     * @return the value of day_off.deleted_at
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column day_off.deleted_at
     *
     * @param deletedAt the value for day_off.deleted_at
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }
}