package jp.co.hjn.merryapi.infrastructure.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EmployeeExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the
     * database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public EmployeeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the
     * database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameFirstIsNull() {
            addCriterion("name_first is null");
            return (Criteria) this;
        }

        public Criteria andNameFirstIsNotNull() {
            addCriterion("name_first is not null");
            return (Criteria) this;
        }

        public Criteria andNameFirstEqualTo(String value) {
            addCriterion("name_first =", value, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstNotEqualTo(String value) {
            addCriterion("name_first <>", value, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstGreaterThan(String value) {
            addCriterion("name_first >", value, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstGreaterThanOrEqualTo(String value) {
            addCriterion("name_first >=", value, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstLessThan(String value) {
            addCriterion("name_first <", value, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstLessThanOrEqualTo(String value) {
            addCriterion("name_first <=", value, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstLike(String value) {
            addCriterion("name_first like", value, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstNotLike(String value) {
            addCriterion("name_first not like", value, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstIn(List<String> values) {
            addCriterion("name_first in", values, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstNotIn(List<String> values) {
            addCriterion("name_first not in", values, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstBetween(String value1, String value2) {
            addCriterion("name_first between", value1, value2, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameFirstNotBetween(String value1, String value2) {
            addCriterion("name_first not between", value1, value2, "nameFirst");
            return (Criteria) this;
        }

        public Criteria andNameLastIsNull() {
            addCriterion("name_last is null");
            return (Criteria) this;
        }

        public Criteria andNameLastIsNotNull() {
            addCriterion("name_last is not null");
            return (Criteria) this;
        }

        public Criteria andNameLastEqualTo(String value) {
            addCriterion("name_last =", value, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastNotEqualTo(String value) {
            addCriterion("name_last <>", value, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastGreaterThan(String value) {
            addCriterion("name_last >", value, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastGreaterThanOrEqualTo(String value) {
            addCriterion("name_last >=", value, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastLessThan(String value) {
            addCriterion("name_last <", value, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastLessThanOrEqualTo(String value) {
            addCriterion("name_last <=", value, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastLike(String value) {
            addCriterion("name_last like", value, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastNotLike(String value) {
            addCriterion("name_last not like", value, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastIn(List<String> values) {
            addCriterion("name_last in", values, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastNotIn(List<String> values) {
            addCriterion("name_last not in", values, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastBetween(String value1, String value2) {
            addCriterion("name_last between", value1, value2, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameLastNotBetween(String value1, String value2) {
            addCriterion("name_last not between", value1, value2, "nameLast");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaIsNull() {
            addCriterion("name_first_kana is null");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaIsNotNull() {
            addCriterion("name_first_kana is not null");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaEqualTo(String value) {
            addCriterion("name_first_kana =", value, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaNotEqualTo(String value) {
            addCriterion("name_first_kana <>", value, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaGreaterThan(String value) {
            addCriterion("name_first_kana >", value, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaGreaterThanOrEqualTo(String value) {
            addCriterion("name_first_kana >=", value, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaLessThan(String value) {
            addCriterion("name_first_kana <", value, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaLessThanOrEqualTo(String value) {
            addCriterion("name_first_kana <=", value, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaLike(String value) {
            addCriterion("name_first_kana like", value, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaNotLike(String value) {
            addCriterion("name_first_kana not like", value, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaIn(List<String> values) {
            addCriterion("name_first_kana in", values, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaNotIn(List<String> values) {
            addCriterion("name_first_kana not in", values, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaBetween(String value1, String value2) {
            addCriterion("name_first_kana between", value1, value2, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameFirstKanaNotBetween(String value1, String value2) {
            addCriterion("name_first_kana not between", value1, value2, "nameFirstKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaIsNull() {
            addCriterion("name_last_kana is null");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaIsNotNull() {
            addCriterion("name_last_kana is not null");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaEqualTo(String value) {
            addCriterion("name_last_kana =", value, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaNotEqualTo(String value) {
            addCriterion("name_last_kana <>", value, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaGreaterThan(String value) {
            addCriterion("name_last_kana >", value, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaGreaterThanOrEqualTo(String value) {
            addCriterion("name_last_kana >=", value, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaLessThan(String value) {
            addCriterion("name_last_kana <", value, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaLessThanOrEqualTo(String value) {
            addCriterion("name_last_kana <=", value, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaLike(String value) {
            addCriterion("name_last_kana like", value, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaNotLike(String value) {
            addCriterion("name_last_kana not like", value, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaIn(List<String> values) {
            addCriterion("name_last_kana in", values, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaNotIn(List<String> values) {
            addCriterion("name_last_kana not in", values, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaBetween(String value1, String value2) {
            addCriterion("name_last_kana between", value1, value2, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andNameLastKanaNotBetween(String value1, String value2) {
            addCriterion("name_last_kana not between", value1, value2, "nameLastKana");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionIsNull() {
            addCriterion("employee_position is null");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionIsNotNull() {
            addCriterion("employee_position is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionEqualTo(Integer value) {
            addCriterion("employee_position =", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNotEqualTo(Integer value) {
            addCriterion("employee_position <>", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionGreaterThan(Integer value) {
            addCriterion("employee_position >", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionGreaterThanOrEqualTo(Integer value) {
            addCriterion("employee_position >=", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionLessThan(Integer value) {
            addCriterion("employee_position <", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionLessThanOrEqualTo(Integer value) {
            addCriterion("employee_position <=", value, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionIn(List<Integer> values) {
            addCriterion("employee_position in", values, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNotIn(List<Integer> values) {
            addCriterion("employee_position not in", values, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionBetween(Integer value1, Integer value2) {
            addCriterion("employee_position between", value1, value2, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andEmployeePositionNotBetween(Integer value1, Integer value2) {
            addCriterion("employee_position not between", value1, value2, "employeePosition");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIsNull() {
            addCriterion("system_role is null");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIsNotNull() {
            addCriterion("system_role is not null");
            return (Criteria) this;
        }

        public Criteria andSystemRoleEqualTo(Integer value) {
            addCriterion("system_role =", value, "systemRole");
            return (Criteria) this;
        }

        public Criteria andSystemRoleNotEqualTo(Integer value) {
            addCriterion("system_role <>", value, "systemRole");
            return (Criteria) this;
        }

        public Criteria andSystemRoleGreaterThan(Integer value) {
            addCriterion("system_role >", value, "systemRole");
            return (Criteria) this;
        }

        public Criteria andSystemRoleGreaterThanOrEqualTo(Integer value) {
            addCriterion("system_role >=", value, "systemRole");
            return (Criteria) this;
        }

        public Criteria andSystemRoleLessThan(Integer value) {
            addCriterion("system_role <", value, "systemRole");
            return (Criteria) this;
        }

        public Criteria andSystemRoleLessThanOrEqualTo(Integer value) {
            addCriterion("system_role <=", value, "systemRole");
            return (Criteria) this;
        }

        public Criteria andSystemRoleIn(List<Integer> values) {
            addCriterion("system_role in", values, "systemRole");
            return (Criteria) this;
        }

        public Criteria andSystemRoleNotIn(List<Integer> values) {
            addCriterion("system_role not in", values, "systemRole");
            return (Criteria) this;
        }

        public Criteria andSystemRoleBetween(Integer value1, Integer value2) {
            addCriterion("system_role between", value1, value2, "systemRole");
            return (Criteria) this;
        }

        public Criteria andSystemRoleNotBetween(Integer value1, Integer value2) {
            addCriterion("system_role not between", value1, value2, "systemRole");
            return (Criteria) this;
        }

        public Criteria andPostalCodeIsNull() {
            addCriterion("postal_code is null");
            return (Criteria) this;
        }

        public Criteria andPostalCodeIsNotNull() {
            addCriterion("postal_code is not null");
            return (Criteria) this;
        }

        public Criteria andPostalCodeEqualTo(String value) {
            addCriterion("postal_code =", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotEqualTo(String value) {
            addCriterion("postal_code <>", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeGreaterThan(String value) {
            addCriterion("postal_code >", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeGreaterThanOrEqualTo(String value) {
            addCriterion("postal_code >=", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeLessThan(String value) {
            addCriterion("postal_code <", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeLessThanOrEqualTo(String value) {
            addCriterion("postal_code <=", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeLike(String value) {
            addCriterion("postal_code like", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotLike(String value) {
            addCriterion("postal_code not like", value, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeIn(List<String> values) {
            addCriterion("postal_code in", values, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotIn(List<String> values) {
            addCriterion("postal_code not in", values, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeBetween(String value1, String value2) {
            addCriterion("postal_code between", value1, value2, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPostalCodeNotBetween(String value1, String value2) {
            addCriterion("postal_code not between", value1, value2, "postalCode");
            return (Criteria) this;
        }

        public Criteria andPrefecturesIsNull() {
            addCriterion("prefectures is null");
            return (Criteria) this;
        }

        public Criteria andPrefecturesIsNotNull() {
            addCriterion("prefectures is not null");
            return (Criteria) this;
        }

        public Criteria andPrefecturesEqualTo(String value) {
            addCriterion("prefectures =", value, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesNotEqualTo(String value) {
            addCriterion("prefectures <>", value, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesGreaterThan(String value) {
            addCriterion("prefectures >", value, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesGreaterThanOrEqualTo(String value) {
            addCriterion("prefectures >=", value, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesLessThan(String value) {
            addCriterion("prefectures <", value, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesLessThanOrEqualTo(String value) {
            addCriterion("prefectures <=", value, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesLike(String value) {
            addCriterion("prefectures like", value, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesNotLike(String value) {
            addCriterion("prefectures not like", value, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesIn(List<String> values) {
            addCriterion("prefectures in", values, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesNotIn(List<String> values) {
            addCriterion("prefectures not in", values, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesBetween(String value1, String value2) {
            addCriterion("prefectures between", value1, value2, "prefectures");
            return (Criteria) this;
        }

        public Criteria andPrefecturesNotBetween(String value1, String value2) {
            addCriterion("prefectures not between", value1, value2, "prefectures");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesIsNull() {
            addCriterion("municipalities is null");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesIsNotNull() {
            addCriterion("municipalities is not null");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesEqualTo(String value) {
            addCriterion("municipalities =", value, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesNotEqualTo(String value) {
            addCriterion("municipalities <>", value, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesGreaterThan(String value) {
            addCriterion("municipalities >", value, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesGreaterThanOrEqualTo(String value) {
            addCriterion("municipalities >=", value, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesLessThan(String value) {
            addCriterion("municipalities <", value, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesLessThanOrEqualTo(String value) {
            addCriterion("municipalities <=", value, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesLike(String value) {
            addCriterion("municipalities like", value, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesNotLike(String value) {
            addCriterion("municipalities not like", value, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesIn(List<String> values) {
            addCriterion("municipalities in", values, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesNotIn(List<String> values) {
            addCriterion("municipalities not in", values, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesBetween(String value1, String value2) {
            addCriterion("municipalities between", value1, value2, "municipalities");
            return (Criteria) this;
        }

        public Criteria andMunicipalitiesNotBetween(String value1, String value2) {
            addCriterion("municipalities not between", value1, value2, "municipalities");
            return (Criteria) this;
        }

        public Criteria andAddress1IsNull() {
            addCriterion("address1 is null");
            return (Criteria) this;
        }

        public Criteria andAddress1IsNotNull() {
            addCriterion("address1 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress1EqualTo(String value) {
            addCriterion("address1 =", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotEqualTo(String value) {
            addCriterion("address1 <>", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1GreaterThan(String value) {
            addCriterion("address1 >", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1GreaterThanOrEqualTo(String value) {
            addCriterion("address1 >=", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1LessThan(String value) {
            addCriterion("address1 <", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1LessThanOrEqualTo(String value) {
            addCriterion("address1 <=", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1Like(String value) {
            addCriterion("address1 like", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotLike(String value) {
            addCriterion("address1 not like", value, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1In(List<String> values) {
            addCriterion("address1 in", values, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotIn(List<String> values) {
            addCriterion("address1 not in", values, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1Between(String value1, String value2) {
            addCriterion("address1 between", value1, value2, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress1NotBetween(String value1, String value2) {
            addCriterion("address1 not between", value1, value2, "address1");
            return (Criteria) this;
        }

        public Criteria andAddress2IsNull() {
            addCriterion("address2 is null");
            return (Criteria) this;
        }

        public Criteria andAddress2IsNotNull() {
            addCriterion("address2 is not null");
            return (Criteria) this;
        }

        public Criteria andAddress2EqualTo(String value) {
            addCriterion("address2 =", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotEqualTo(String value) {
            addCriterion("address2 <>", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2GreaterThan(String value) {
            addCriterion("address2 >", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2GreaterThanOrEqualTo(String value) {
            addCriterion("address2 >=", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2LessThan(String value) {
            addCriterion("address2 <", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2LessThanOrEqualTo(String value) {
            addCriterion("address2 <=", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2Like(String value) {
            addCriterion("address2 like", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotLike(String value) {
            addCriterion("address2 not like", value, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2In(List<String> values) {
            addCriterion("address2 in", values, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotIn(List<String> values) {
            addCriterion("address2 not in", values, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2Between(String value1, String value2) {
            addCriterion("address2 between", value1, value2, "address2");
            return (Criteria) this;
        }

        public Criteria andAddress2NotBetween(String value1, String value2) {
            addCriterion("address2 not between", value1, value2, "address2");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNull() {
            addCriterion("phone_number is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIsNotNull() {
            addCriterion("phone_number is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberEqualTo(String value) {
            addCriterion("phone_number =", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotEqualTo(String value) {
            addCriterion("phone_number <>", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThan(String value) {
            addCriterion("phone_number >", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberGreaterThanOrEqualTo(String value) {
            addCriterion("phone_number >=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThan(String value) {
            addCriterion("phone_number <", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLessThanOrEqualTo(String value) {
            addCriterion("phone_number <=", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberLike(String value) {
            addCriterion("phone_number like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotLike(String value) {
            addCriterion("phone_number not like", value, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberIn(List<String> values) {
            addCriterion("phone_number in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotIn(List<String> values) {
            addCriterion("phone_number not in", values, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberBetween(String value1, String value2) {
            addCriterion("phone_number between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andPhoneNumberNotBetween(String value1, String value2) {
            addCriterion("phone_number not between", value1, value2, "phoneNumber");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Integer value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Integer value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Integer value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Integer value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Integer value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Integer> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Integer> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Integer value1, Integer value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Integer value1, Integer value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIsNull() {
            addCriterion("deleted_at is null");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIsNotNull() {
            addCriterion("deleted_at is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedAtEqualTo(Date value) {
            addCriterion("deleted_at =", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotEqualTo(Date value) {
            addCriterion("deleted_at <>", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtGreaterThan(Date value) {
            addCriterion("deleted_at >", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("deleted_at >=", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtLessThan(Date value) {
            addCriterion("deleted_at <", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtLessThanOrEqualTo(Date value) {
            addCriterion("deleted_at <=", value, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtIn(List<Date> values) {
            addCriterion("deleted_at in", values, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotIn(List<Date> values) {
            addCriterion("deleted_at not in", values, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtBetween(Date value1, Date value2) {
            addCriterion("deleted_at between", value1, value2, "deletedAt");
            return (Criteria) this;
        }

        public Criteria andDeletedAtNotBetween(Date value1, Date value2) {
            addCriterion("deleted_at not between", value1, value2, "deletedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the
     * database table employee
     *
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table employee
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 24 23:49:01 JST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}