package jp.co.hjn.merryapi.infrastructure.mapper;

import java.util.List;
import jp.co.hjn.merryapi.infrastructure.model.DayOff;
import jp.co.hjn.merryapi.infrastructure.model.DayOffExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DayOffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    long countByExample(DayOffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    int deleteByExample(DayOffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    int insert(DayOff row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    int insertSelective(DayOff row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    List<DayOff> selectByExample(DayOffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    DayOff selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    int updateByExampleSelective(@Param("row") DayOff row, @Param("example") DayOffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    int updateByExample(@Param("row") DayOff row, @Param("example") DayOffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    int updateByPrimaryKeySelective(DayOff row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table day_off
     *
     * @mbg.generated Sat Aug 08 12:11:18 JST 2026
     */
    int updateByPrimaryKey(DayOff row);
}