package jp.co.hjn.merryapi.infrastructure.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import jp.co.hjn.merryapi.infrastructure.model.Employee;
import jp.co.hjn.merryapi.infrastructure.model.EmployeeExample;

@Mapper
public interface EmployeeMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int insert(Employee row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int insertSelective(Employee row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int updateByExampleSelective(@Param("row") Employee row, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int updateByExample(@Param("row") Employee row, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int updateByPrimaryKeySelective(Employee row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to
     * the database table employee
     * 
     * @mbg.generated Wed Jan 25 00:14:04 JST 2023
     */
    int updateByPrimaryKey(Employee row);
}